### ISSUE TITLE
Cannot use shellcheck plugin

### ISSUE THREAD

**Issue by praetp** [elastic/gradle-plugins#35]
Trying to use 

> id("co.elastic.cli.shellcheck") version "1.0.5"

but getting
  > Could not resolve koalaman/shellcheck:shellcheck:v0.10.0.
         > Could not get resource 'https://artifactory.elastic.dev/artifactory/github-release-proxy/koalaman/shellcheck/releases/download/v0.10.0/shellcheck-v0.10.0.linux.x86_64.tar.xz'.
            > Could not HEAD 'https://artifactory.elastic.dev/artifactory/github-release-proxy/koalaman/shellcheck/releases/download/v0.10.0/shellcheck-v0.10.0.linux.x86_64.tar.xz'. Received status code 401 from server:

**Comment by rhass** [comment]
@elastic/release-eng Do we publish these plugins on maven central or some other public artifact store?

**Comment by imkarrer** [comment]
They are published to plugins.gradle.org.

https://plugins.gradle.org/search?term=co.elastic

**Comment by imkarrer** [comment]
I see that you're trying to it our internal artifactory versus your own.

https://github.com/elastic/gradle-plugins/blob/main/plugins/cli/README.md#usage

>         baseURL.set(java.net.URL("link to your own generic artifactory repo"))
